services:
  - type: web
    name: Frozen-Music
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ASSISTANT_ID
        sync: false
      - key: API_BASE_URL
        sync: false
      



